In [10]:
%%time

import numpy as np



crop = np.array([10,20,30])
weights = np.array([0.3,0.2,0.5])

print(np.dot(crop,weights))




22.0
CPU times: user 307 µs, sys: 185 µs, total: 492 µs
Wall time: 317 µs


In [14]:
%%time
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

print(weights.shape)
print(climate_data.shape)

arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

print(arr3.shape)

print(climate_data @ weights)

(3,)
(5, 3)
(2, 2, 3)
[56.8 76.9 81.9 57.7 74.9]
CPU times: user 713 µs, sys: 251 µs, total: 964 µs
Wall time: 818 µs


In [16]:
import urllib.request

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [17]:
climate_data.shape


(10000, 3)

In [18]:
weights = np.array([0.3,0.2,0.5])
yields = climate_data @ weights

In [19]:
print(yields)
print(yields.shape)

[72.2 59.7 65.2 ... 71.1 80.7 73.4]
(10000,)


In [20]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

In [21]:
climate_results.shape

(10000, 4)

In [22]:
np.savetxt('climate_results.txt', 
           climate_results, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')

In [23]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

arr4 = np.array([4, 5, 6, 7])


In [24]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [28]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36.9, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [29]:
print(arr3.shape)

(3, 2, 4)


In [30]:
arr3[1, 1, 2]

36.9

In [37]:
# Subarray using ranges
arr3[1:, 0:1, :2].shape

(2, 1, 2)

In [39]:
arr3[1:, 0:1, :2].shape

(2, 1, 2)

In [40]:
# Mixing indices and ranges
arr3[1:, 1, 3]

array([18., 43.])

In [41]:
# Mixing indices and ranges
arr3[1:, 1, :3]

array([[63. , 92. , 36.9],
       [17. , 18. , 19.5]])

In [42]:
np.random.rand(10)

array([0.07186201, 0.74873911, 0.12221562, 0.38958854, 0.55821426,
       0.42362472, 0.01537397, 0.27586025, 0.93290179, 0.32405731])

In [45]:
np.random.randn(10)

array([ 1.05024585,  0.93065702, -1.12056474, -0.02235622,  1.060557  ,
       -0.0903628 ,  0.71945048, -1.81423803,  0.71186128,  1.51218771])

In [46]:
np.full([2,3],45)

array([[45, 45, 45],
       [45, 45, 45]])

In [50]:
np.arange(10,90,3).reshape(3,3,3)


array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [52]:
np.linspace(3,9,9)

array([3.  , 3.75, 4.5 , 5.25, 6.  , 6.75, 7.5 , 8.25, 9.  ])

# Function 1

# Exercises

In [53]:
import numpy as np

In [58]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/italogs/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/italogs/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/italogs/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/italogs/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/italogs/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/italogs/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/italogs/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/italogs/opt/anaconda3/include']
None


In [62]:
np.full([10],None)

print(np.full([10],None).nbytes)

80


In [63]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [71]:
arr1 = (np.full(10,None))
arr1[4] = 1
arr1

array([None, None, None, None, 1, None, None, None, None, None],
      dtype=object)

In [72]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [77]:
np.flip(np.arange(10,50))

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [79]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
arr1 = np.array([1,2,0,0,4,0])
# np.info(np.where)
np.where(arr1 != 0)

(array([0, 1, 4]),)

In [89]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
np.random.rand(3,3,3)

array([[[0.43571976, 0.65501788, 0.45316279],
        [0.03255548, 0.24767106, 0.85291856],
        [0.86663551, 0.96055012, 0.63323849]],

       [[0.42614958, 0.75188712, 0.7379168 ],
        [0.50424621, 0.86024885, 0.19935888],
        [0.83291276, 0.53079827, 0.12559906]],

       [[0.22575967, 0.45193942, 0.92196514],
        [0.51955837, 0.37905738, 0.82514105],
        [0.44181778, 0.93925266, 0.55542871]]])

In [93]:
np.min(np.random.rand(10,10))
np.max(np.random.rand(10,10))

0.9964895011816584

In [94]:
np.mean(np.random.rand(30))

0.5341594445807997

In [97]:
arr1 = np.full([10,10],1)
arr1[1:9,1:9] = 0
print(arr1)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [112]:
arr1 = np.full([5,5],0)
arr1= np.pad(arr1,pad_width=1,mode='constant', constant_values=1)
print(arr1)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


In [119]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == round(3*0.1))
print(0.1*3)

nan
False
False
nan
True
False
0.30000000000000004


In [123]:
arr1 = np.eye(5,5)
np.diag([1,2,3,4],k=-1)

# np.info(np.diag)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [134]:
arr1 = np.zeros((8,8))
arr1[0:9:2,0:9:2] = 1
arr1[1:9:2,1:9:2] = 1
arr1

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [145]:
arr1 = np.random.rand(6,7,8).reshape(1,6*7*8)
arr1[0,99]

0.7020583022738082

In [154]:
np.info(np.tile)
np.tile(np.array([[1., 0., 1., 0., 1., 0., 1., 0.], [0., 1., 0., 1., 0., 1., 0., 1.]]), (8,8))

 tile(*args, **kwargs)

Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat elements of an a

array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 0., ..., 1., 0., 1.],
       [1., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 1., 0., 1.],
       [1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 0., ..., 1., 0., 1.]])

In [158]:
arr1 = np.random.rand(5,5)

arr1/np.linalg.norm(arr1)


array([[0.15902567, 0.37428179, 0.02584744, 0.08194549, 0.33820215],
       [0.03705   , 0.27841909, 0.28755516, 0.19607747, 0.18621751],
       [0.2594843 , 0.09043266, 0.02869366, 0.19213516, 0.11393337],
       [0.07860284, 0.00934309, 0.13540481, 0.29873957, 0.17037672],
       [0.30288795, 0.19733252, 0.02589236, 0.09964867, 0.26033341]])

In [161]:
rgbadt = np.dtype([('r',np.ubyte), ('g',np.ubyte),('b',np.ubyte),('a',np.ubyte)])

In [184]:
arr1 = np.random.rand(5,3)
arr2 = np.random.rand(3,2)
print(np.matmul(arr1,arr2))

[[1.10773389 1.25157711]
 [0.37646773 0.60531347]
 [0.91692401 1.09895687]
 [0.89618081 1.02135709]
 [0.70104406 0.79086335]]


In [165]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [175]:
Z = np.array([1,2,3])
print(Z**Z)
print(2 << Z)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z)


[ 1  4 27]
[ 4  8 16]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


In [177]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-177-6caa14b62dca>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0)/np.array(0))
<ipython-input-177-6caa14b62dca>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))


In [178]:
np.round(np.array([0.11,0.33333]),2)

array([0.11, 0.33])

In [3]:
arr1 = np.arange(10)
arr2 = np.arange(5,10)
np.intersect1d(arr1,arr2)

array([5, 6, 7, 8, 9])

In [4]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [14]:
import numpy as np
from numpy import *

np.sqrt(-1) == np.emath.sqrt(-1)
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


In [29]:
print(np.datetime64('today','D'))
print(np.datetime64('today','D') - np.timedelta64(1,'D'))
print(np.datetime64('today','D') + np.timedelta64(1,'D'))


2021-01-07
2021-01-06
2021-01-08


In [41]:
print(np.arange('2017-03', '2017-04', dtype='datetime64[D]'))

['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


In [43]:
A = np.ones(3)*1

B = np.ones(3)*2

C = np.ones(3)*3

np.add(A,B,out=B)

np.divide(A,2,out=A)

np.negative(A,out=A)

np.multiply(A,B,out=A)



[[-0.79373547 -0.90120871 -0.51676325]
 [-0.80296873 -0.7969892  -0.68769424]
 [-0.71905294 -0.67100123 -0.76193503]]


In [44]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)

print (np.floor(Z))

print (np.ceil(Z)-1)

print (Z.astype(int))

print (np.trunc(Z))



[9. 5. 9. 2. 3. 7. 7. 7. 9. 6.]
[9. 5. 9. 2. 3. 7. 7. 7. 9. 6.]
[9. 5. 9. 2. 3. 7. 7. 7. 9. 6.]
[9 5 9 2 3 7 7 7 9 6]
[9. 5. 9. 2. 3. 7. 7. 7. 9. 6.]


In [53]:
np.tile(np.array([0,1,2,3,4]),5).reshape(5,5)



def generate():

    for x in range(10):
        yield x
    Z = np.fromiter(generate(),dtype=float,count=-1)

    print(Z)
generate()

<generator object generate at 0x7fe04c7925f0>

In [47]:
np.random.rand(10) * 0.1

array([0.05902832, 0.01249866, 0.04212223, 0.05763849, 0.0218965 ,
       0.05011485, 0.02672539, 0.07977906, 0.06971411, 0.07923451])

In [48]:
np.sort(np.random.rand(10))

array([0.0068057 , 0.12446931, 0.3148093 , 0.40030239, 0.52386294,
       0.54412221, 0.69931693, 0.93802451, 0.96291054, 0.97961896])

In [58]:
%%time
Z = np.arange(10)
np.add.reduce(Z)

CPU times: user 50 µs, sys: 9 µs, total: 59 µs
Wall time: 56 µs


45

In [59]:
%%time
Z = np.arange(10)
np.sum(Z)

CPU times: user 63 µs, sys: 9 µs, total: 72 µs
Wall time: 67.2 µs


45

In [64]:
arr1 = np.random.randint(0,2,5)
arr2 = np.random.randint(0,2,5)

print(arr1==arr2)

[0 1 2 3 4]
[ True  True False  True  True]


In [65]:
Z = np.zeros(10)
Z.flags.writeable = False 
Z[0] = 1

ValueError: assignment destination is read-only

In [66]:
Z = np.random.random((10,2))

X,Y = Z[:,0], Z[:,1]

R = np.sqrt(X**2+Y**2)

T = np.arctan2(Y,X)

print(R)

print(T)

[0.43965118 0.28531712 0.61916795 0.99917488 0.99309545 1.03224883
 0.79357938 0.45732869 0.61782041 1.09419849]
[0.01743324 1.29244699 0.4282052  1.366852   0.13155152 0.41789456
 0.67996423 0.47606502 0.41209281 0.80495406]


In [70]:
arr1 = np.random.rand(10)
Z[Z.argmax()] = 0


In [80]:
Z = np.zeros((5,5), [('x',float), ('y',float)] )
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [82]:
Z = np.arange(100)

v = np.random.uniform(0,100)

index = (np.abs(Z-v)).argmin()

print(Z[index])



81
